Revert r23691: regressions under OS X. Some failures like that:
{{{
[ERROR]: twisted.python.test.test_runtime.PlatformTests.test_isVistaConsistency

Traceback (most recent call last):
  File "/Users/buildbot/Run/buildbot/full2.5-exarkun-osx/Twisted/twisted/python/test/test_runtime.py", line 26, in test_isVistaConsistency
    if platform.isVista():
  File "/Users/buildbot/Run/buildbot/full2.5-exarkun-osx/Twisted/twisted/python/runtime.py", line 85, in isVista
    uname = platform.uname()
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/platform.py", line 1014, in uname
    processor = _syscmd_uname('-p','')
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/platform.py", line 800, in _syscmd_uname
    output = string.strip(f.read())
exceptions.IOError: [Errno 4] Interrupted system call
}}}

Reopens #2881


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@23693 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb