<<EOF Revert r30634 - test suite regression
Reopens #3172

This test failure appears on most platforms:

{{{
===============================================================================
[ERROR]
Traceback (most recent call last):
  File /var/lib/buildbot/twisted/lucid32-py2.7maint/Twisted/twisted/python/test/test_util.py, line 209, in test_currentEUID
    self.assertIn('but uid is already %i' % uid, warnings[0]['message'])
exceptions.NameError: global name 'uid' is not defined

twisted.python.test.test_util.SwitchUIDTest.test_currentEUID
-------------------------------------------------------------------------------
}}}
EOF


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@30635 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb