Revert r29690 - test suite regression
This revision introduced test failures on the without-modules configuration:

{{{
===============================================================================
[ERROR]: twisted.conch.test.test_transport.RandomNumberTestCase.test_excludesLarge

Traceback (most recent call last):
  File "/var/lib/buildbot/twisted/py2.5-without-modules/Twisted/twisted/conch/test/test_transport.py", line 1961, in test_excludesLarge
    transport._generateX(random, 8),
exceptions.AttributeError: class transport has no attribute "_generateX"
===============================================================================
}}}

etc

Reopens #4469


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@29691 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb